### ISSUE TITLE
click event

### ISSUE THREAD

**Issue by cempro** [pokyah/leafletResponsiveElevation#1]
I have very little knowledge with jquery. 
How should I modify the code so that the elevation profile would be auto loaded with page load instead of a user button click action? 

line no. 320 '... $('#hiver').on("click", function() { ...'

Thank you

**Comment by pokyah** [comment]
I'm on my phone. I'll have a look to my old cold tomorrow morning (Belgian time) and let you know how to do this

**Comment by cempro** [comment]
That's what I need. Now it is easier for me to adapt it to my project.
Thank you for your support and quick response.

**Comment by pokyah** [comment]
Great ! Good luck in your project development ! If you need further help, feel free to contact me. Please notify me when your map is finished. I'll be interested to see how it looks like :) And also feel free to mention me in your project description. Thanks !
